POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Jan",
  "surname": "Kowalski"
}



###

GET http://localhost:8080/api/users/2
Accept: application/json

###

GET http://localhost:8080/api/users?lastNameFragment=kow
Accept: application/json

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Microservices in practice (e-book)",
  "description": "Book",
  "price": "100.99 PLN",
  "type": "BOOK"
}

###
GET http://localhost:8080/api/products
Accept: application/json

###